sonar.organization=codeyourfuture
sonar.projectKey=codeyourfuture_gitbot
sonar.projectName=gitbot

sonar.sources=src
sonar.tests=src/**/*.test.ts

sonar.coverage.exclusions=src/**/*.test.ts
sonar.javascript.lcov.reportPaths=./reports/coverage/lcov.info
